name: Run packer

on:
  push:
    branches:
        - 'main'
jobs:
  packer_build:
    
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      # # validate templates
      # - name: Validate Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: validate
      #     arguments: -syntax-only
      #     target: aws-linux.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build 
          arguments: "-color=false -on-error=abort"
          target: aws-packer.pkr.hcl
        env:
          PACKER_LOG: 1


      - name: Create new launch template version
        run: |
          aws ec2 create-launch-template-version --launch-template-name asg_launch_config --source-version ${{ github.sha }} --region us-east-1

      - name: Initiate instance refresh
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name asg_launch_config --preferences "MinHealthyPercentage=75,InstanceWarmup=300" --region us-east-1     
        

